=== deeppaz/ava-sipi/packages/schema/json/mass-balance.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "generatedAt": {
      "type": "string",
      "format": "date-time",
      "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$"
    },
    "source": {
      "type": "string"
    },
    "sourceUrl": {
      "type": "string"
    },
    "regions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "region": {
            "type": "string"
          },
          "regionName": {
            "type": "string"
          },
          "year": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "mwe": {
            "type": "number"
          },
          "gt": {
            "type": "number"
          }
        },
        "required": [
          "region",
          "regionName",
          "year",
          "mwe"
        ]
      }
    }
  },
  "required": [
    "generatedAt",
    "source",
    "sourceUrl",
    "regions"
  ],
  "$id": "https://ava-sipi.dev/schema/mass-balance.json",
  "title": "mass-balance"
}

=== deeppaz/ava-sipi/data/samples/glaciers/latest/massbalance.json
{"generatedAt":"2026-09-02T21:54:42Z","source":"WGMS annual mass-change estimates 2026-02-10","sourceUrl":"https://doi.org/10.5904/wgms-amce-2026-02-10","regions":[{"region":"01","regionName":"Alaska","year":2025,"mwe":-0.711,"gt":-56.799},{"region":"01","regionName":"Alaska","year":2024,"mwe":-0.939,"gt":-75.434},{"region":"01","regionName":"Alaska","year":2023,"mwe":-1.588,"gt":-128.106},{"region":"01","regionName":"Alaska","year":2022,"mwe":-1.071,"gt":-86.833},{"region":"01","regionName":"Alaska","year":2021,"mwe":-0.939,"gt":-76.46},{"region":"01","regionName":"Alaska","year":2020,"mwe":-0.933,"gt":-76.35},{"region":"01","regionName":"Alaska","year":2019,"mwe":-1.982,"gt":-163.003},{"region":"01","regionName":"Alaska","year":2018,"mwe":-1.414,"gt":-116.902},{"region":"01","regionName":"Alaska","year":2017,"mwe":-1.276,"gt":-106.01},{"region":"01","regionName":"Alaska","year":2016,"mwe":-1.028,"gt":-85.816},{"region":"01","regionName":"Alaska","year":2015,"mwe":-1.437,"gt":-120.5},{"region":"01","regionName":"Alaska","year":2014,"mwe":-1.083,"gt":-91.223},{"region":"02","regionName":"Western Canada & USA","year":2025,"mwe":-1.86,"gt":-23.724},{"region":"02","regionName":"Western Canada & USA","year":2024,"mwe":-1.496,"gt":-19.187},{"region":"02","regionName":"Western Canada & USA","year":2023,"mwe":-2.557,"gt":-32.963},{"region":"02","regionName":"Western Canada & USA","year":2022,"mwe":-0.701,"gt":-9.088},{"region":"02","regionName":"Western Canada & USA","year":2021,"mwe":-1.489,"gt":-19.408},{"region":"02","regionName":"Western Canada & USA","year":2020,"mwe":-0.647,"gt":-8.475},{"region":"02","regionName":"Western Canada & USA","year":2019,"mwe":-1.585,"gt":-20.882},{"region":"02","regionName":"Western Canada & USA","year":2018,"mwe":-0.877,"gt":-11.613},{"region":"02","regionName":"Western Canada & USA","year":2017,"mwe":-0.678,"gt":-9.034},{"region":"02","regionName":"Western Canada & USA","year":2016,"mwe":-0.914,"gt":-12.245},{"region":"02","regionName":"Western Canada & USA","year":2015,"mwe":-1.715,"gt":-23.097},{"region":"02","regionName":"Western Canada & USA","year":2014,"mwe":-0.93,"gt":-12.586},{"region":"03","regionName":"Arctic Canada North","year":2025,"mwe":-0.057,"gt":-5.89},{"region":"03","regionName":"Arctic Canada North","year":2024,"mwe":-0.238,"gt":-24.566},{"region":"03","regionName":"Arctic Canada North","year":2023,"mwe":-0.597,"gt":-61.745},{"region":"03","regionName":"Arctic Canada North","year":2022,"mwe":-0.494,"gt":-51.132},{"region":"03","regionName":"Arctic Canada North","year":2021,"mwe":0.023,"gt":2.344},{"region":"03","regionName":"Arctic Canada North","year":2020,"mwe":-0.588,"gt":-60.873},{"region":"03","regionName":"Arctic Canada North","year":2019,"mwe":-0.605,"gt":-62.706},{"region":"03","regionName":"Arctic Canada North","year":2018,"mwe":0.16,"gt":16.603},{"region":"03","regionName":"Arctic Canada North","year":2017,"mwe":0.086,"gt":8.898},{"region":"03","regionName":"Arctic Canada North","year":2016,"mwe":-0.456,"gt":-47.382},{"region":"03","regionName":"Arctic Canada North","year":2015,"mwe":-0.63,"gt":-65.432},{"region":"03","regionName":"Arctic Canada North","year":2014,"mwe":-0.153,"gt":-15.935},{"region":"04","regionName":"Arctic Canada South","year":2025,"mwe":-0.31,"gt":-12.422},{"region":"04","regionName":"Arctic Canada South","year":2024,"mwe":-0.492,"gt":-19.749},{"region":"04","regionName":"Arctic Canada South","year":2023,"mwe":-0.879,"gt":-35.28},{"region":"04","regionName":"Arctic Canada South","year":2022,"mwe":-0.784,"gt":-31.513},{"region":"04","regionName":"Arctic Canada South","year":2021,"mwe":-0.187,"gt":-7.52},{"region":"04","regionName":"Arctic Canada South","year":2020,"mwe":-0.845,"gt":-34.003},{"region":"04","regionName":"Arctic Canada South","year":2019,"mwe":-0.777,"gt":-31.293},{"region":"04","regionName":"Arctic Canada South","year":2018,"mwe":-0.068,"gt":-2.724},{"region":"04","regionName":"Arctic Canada South","year":2017,"mwe":-0.182,"gt":-7.351},{"region":"04","regionName":"Arctic Canada South","year":2016,"mwe":-0.727,"gt":-29.352},{"region":"04","regionName":"Arctic Canada South","year":2015,"mwe":-0.867,"gt":-35.037},{"region":"04","regionName":"Arctic Canada South","year":2014,"mwe":-0.38,"gt":-15.383},{"region":"05","regionName":"Greenland Periphery","year":2025,"mwe":-0.401,"gt":-29.306},{"region":"05","regionName":"Greenland Periphery","year":2024,"mwe":-0.461,"gt":-33.94},{"region":"05","regionName":"Greenland Periphery","year":2023,"mwe":-0.941,"gt":-69.829},{"region":"05","regionName":"Greenland Periphery","year":2022,"mwe":-0.545,"gt":-40.769},{"region":"05","regionName":"Greenland Periphery","year":2021,"mwe":-0.501,"gt":-37.794},{"region":"05","regionName":"Greenland Periphery","year":2020,"mwe":-0.615,"gt":-46.827},{"region":"05","regionName":"Greenland Periphery","year":2019,"mwe":-0.936,"gt":-71.811},{"region":"05","regionName":"Greenland Periphery","year":2018,"mwe":0.417,"gt":32.293},{"region":"05","regionName":"Greenland Periphery","year":2017,"mwe":-0.07,"gt":-5.474},{"region":"05","regionName":"Greenland Periphery","year":2016,"mwe":-0.755,"gt":-59.395},{"region":"05","regionName":"Greenland Periphery","year":2015,"mwe":-0.128,"gt":-10.164},{"region":"05","regionName":"Greenland Periphery","year":2014,"mwe":-0.083,"gt":-6.599},{"region":"06","regionName":"Iceland","year":2025,"mwe":-1.553,"gt":-15.636},{"region":"06","regionName":"Iceland","year":2024,"mwe":-0.656,"gt":-6.628},{"region":"06","regionName":"Iceland","year":2023,"mwe":-1.144,"gt":-11.606},{"region":"06","regionName":"Iceland","year":2022,"mwe":-0.267,"gt":-2.715},{"region":"06","regionName":"Iceland","year":2021,"mwe":-1.324,"gt":-13.528},{"region":"06","regionName":"Iceland","year":2020,"mwe":-0.524,"gt":-5.368},{"region":"06","regionName":"Iceland","year":2019,"mwe":-1.239,"gt":-12.749},{"region":"06","regionName":"Iceland","year":2018,"mwe":-0.154,"gt":-1.59},{"region":"06","regionName":"Iceland","year":2017,"mwe":-0.385,"gt":-3.986},{"region":"06","regionName":"Iceland","year":2016,"mwe":-0.987,"gt":-10.263},{"region":"06","regionName":"Iceland","year":2015,"mwe":0.66,"gt":6.892},{"region":"06","regionName":"Iceland","year":2014,"mwe":-0.823,"gt":-8.628},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2025,"mwe":-1.208,"gt":-39.058},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2024,"mwe":-1.603,"gt":-51.957},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2023,"mwe":-0.639,"gt":-20.76},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2022,"mwe":-1.184,"gt":-38.555},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2021,"mwe":-0.435,"gt":-14.205},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2020,"mwe":-1.283,"gt":-42.021},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2019,"mwe":-0.398,"gt":-13.073},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2018,"mwe":-0.52,"gt":-17.11},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2017,"mwe":-0.323,"gt":-10.658},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2016,"mwe":-0.718,"gt":-23.772},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2015,"mwe":-0.432,"gt":-14.338},{"region":"07","regionName":"Svalbard & Jan Mayen","year":2014,"mwe":0.014,"gt":0.466},{"region":"08","regionName":"Scandinavia","year":2025,"mwe":-0.386,"gt":-1.07},{"region":"08","regionName":"Scandinavia","year":2024,"mwe":-2.306,"gt":-6.408},{"region":"08","regionName":"Scandinavia","year":2023,"mwe":-1.145,"gt":-3.19},{"region":"08","regionName":"Scandinavia","year":2022,"mwe":-0.253,"gt":-0.707},{"region":"08","regionName":"Scandinavia","year":2021,"mwe":-0.917,"gt":-2.569},{"region":"08","regionName":"Scandinavia","year":2020,"mwe":0.566,"gt":1.59},{"region":"08","regionName":"Scandinavia","year":2019,"mwe":-0.586,"gt":-1.65},{"region":"08","regionName":"Scandinavia","year":2018,"mwe":-1.539,"gt":-4.346},{"region":"08","regionName":"Scandinavia","year":2017,"mwe":0.315,"gt":0.893},{"region":"08","regionName":"Scandinavia","year":2016,"mwe":-0.487,"gt":-1.383},{"region":"08","regionName":"Scandinavia","year":2015,"mwe":0.692,"gt":1.971},{"region":"08","regionName":"Scandinavia","year":2014,"mwe":-1.027,"gt":-2.933},{"region":"09","regionName":"Russian Arctic","year":2025,"mwe":-1.097,"gt":-55.513},{"region":"09","regionName":"Russian Arctic","year":2024,"mwe":-1.5,"gt":-75.994},{"region":"09","regionName":"Russian Arctic","year":2023,"mwe":-0.527,"gt":-26.726},{"region":"09","regionName":"Russian Arctic","year":2022,"mwe":-1.092,"gt":-55.383},{"region":"09","regionName":"Russian Arctic","year":2021,"mwe":-0.346,"gt":-17.576},{"region":"09","regionName":"Russian Arctic","year":2020,"mwe":-1.18,"gt":-59.966},{"region":"09","regionName":"Russian Arctic","year":2019,"mwe":-0.296,"gt":-15.045},{"region":"09","regionName":"Russian Arctic","year":2018,"mwe":-0.419,"gt":-21.32},{"region":"09","regionName":"Russian Arctic","year":2017,"mwe":-0.26,"gt":-13.225},{"region":"09","regionName":"Russian Arctic","year":2016,"mwe":-0.696,"gt":-35.486},{"region":"09","regionName":"Russian Arctic","year":2015,"mwe":-0.307,"gt":-15.672},{"region":"09","regionName":"Russian Arctic","year":2014,"mwe":0.193,"gt":9.831},{"region":"10","regionName":"North Asia","year":2025,"mwe":-0.848,"gt":-1.899},{"region":"10","regionName":"North Asia","year":2024,"mwe":-1.003,"gt":-2.257},{"region":"10","regionName":"North Asia","year":2023,"mwe":-0.975,"gt":-2.203},{"region":"10","regionName":"North Asia","year":2022,"mwe":-0.897,"gt":-2.036},{"region":"10","regionName":"North Asia","year":2021,"mwe":-0.654,"gt":-1.491},{"region":"10","regionName":"North Asia","year":2020,"mwe":-0.66,"gt":-1.509},{"region":"10","regionName":"North Asia","year":2019,"mwe":-0.879,"gt":-2.021},{"region":"10","regionName":"North Asia","year":2018,"mwe":-0.861,"gt":-1.986},{"region":"10","regionName":"North Asia","year":2017,"mwe":-0.945,"gt":-2.192},{"region":"10","regionN
