=== deeppaz/ava-sipi/packages/schema/json/reservoir-series.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "unit": {
      "type": "string",
      "const": "km2"
    },
    "points": {
      "type": "array",
      "items": {
        "type": "array",
        "prefixItems": [
          {
            "type": "string",
            "format": "date",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"
          },
          {
            "type": "number",
            "minimum": 0
          }
        ],
        "items": false,
        "minItems": 2,
        "maxItems": 2
      }
    },
    "areaP95Km2": {
      "type": "number",
      "minimum": 0
    }
  },
  "required": [
    "id",
    "unit",
    "points"
  ],
  "$id": "https://ava-sipi.dev/schema/reservoir-series.json",
  "title": "reservoir-series"
}

=== deeppaz/ava-sipi/data/samples/reservoirs/latest/series/88197.json
{"id":"88197","unit":"km2","points":[["2023-09-01",47.2255],["2023-10-01",46.5513],["2023-11-01",48.526],["2023-12-01",56.6667],["2024-01-01",56.8278],["2024-02-01",53.8087],["2024-03-01",50.8178],["2024-04-01",52.4707],["2024-05-01",56.0939],["2024-06-01",55.7897],["2024-07-01",51.9633],["2024-08-01",45.8412],["2024-09-01",40.2182],["2024-10-01",39.042],["2024-11-01",42.4139],["2024-12-01",47.6476],["2025-01-01",52.2565],["2025-02-01",52.4938],["2025-03-01",52.045],["2025-04-01",53.0717],["2025-05-01",55.9605],["2025-06-01",55.8105],["2025-07-01",51.5044],["2025-08-01",46.3354],["2025-09-01",43.0085],["2025-10-01",40.09],["2025-11-01",46.134],["2025-12-01",47.1537],["2026-01-01",55.3164],["2026-02-01",52.6007],["2026-03-01",52.1631],["2026-04-01",53.2563],["2026-05-01",55.835],["2026-06-01",53.9287],["2026-07-01",49.2512]],"areaP95Km2":56.0939}
